config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
    # resources :reviews, shallow: true -> will give you index, new, create

    collection do
      get 'top'
    end

    member do
      get 'chef'
    end
  end

  resources :reviews, only: [ :edit, :update, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, presence: true, inclusion: ["chinese", "italian", "japanese", "french", "belgian"]
  validates :overall_rating, presence:true, inclusion: [0,1,2,3,4,5]
  # validates :chef_name, presence:true
  # validates :chef_bio, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true, length: { minimum: 5 }
  validates :rating, presence: true,  numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy, :chef]

  # GET /restaurants
  def index
    @restaurants = Restaurant.all
    @restaurants.each do |r|
      r["overall_rating"] = ((r.reviews.map{|review| review.rating}.sum)/r.reviews.count).round()
    end
  end

  def top
    @restaurants = Restaurant.where("overall_rating >= 3").limit(5)
  end

  # GET /restaurants/1
  def show
    r = @restaurant
    r["overall_rating"] = ((r.reviews.map{|review| review.rating}.sum)/r.reviews.count).round()
  end

  def chef
    # @restaurant -> already available because we added to the before action
    
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
      # redirect_to restaurants_urlt, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /restaurants/1
  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /restaurants/1
  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category, :chef_name, :chef_bio, :overall_rating)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:new, :create]
  before_action :set_review, only: [:edit, :update, :destroy]

  def index

  end

  def new
    @review = Review.new
    
  end
  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to @restaurant, notice: 'Review Added!.'
    else
      render :new
    end
  end
  def edit
  end

  def update
    if @review.update(review_params)
      @restaurant = @review.restaurant
      redirect_to @restaurant
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    @restaurant = @review.restaurant
    redirect_to @restaurant
  end

  private
  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
  
  
  def set_review
      @review = Review.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category, collection:["chinese", "italian", "japanese", "french", "belgian"] %>
    <%= f.input :chef_name %>
    <%= f.input :chef_bio %>
    

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/_list.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone number</th>
      <th>Category</th>
      <th>Rating</th> 
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.phone_number %></td>
        <td><%= restaurant.category %></td>
        <td><%= "⭐" * restaurant.overall_rating %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/chef.html.erb
<div class="row justify-content-center">
  <div class="col-6">
    <div class="card" style="width: 18rem;">
      <h1>Meet the chef: <%= @restaurant.chef_name %></h1>
      <div class="card-body">
        <h3>About the chef:</h3>
        <p>
          <%= @restaurant.chef_bio %>
        </p>
        <%= link_to 'Back', restaurants_path %>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<%= render 'list' %>

<br>
<%= link_to 'Our Top Restaurants', top_restaurants_path  %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Category:</strong>
  <%= @restaurant.category %>
</p>

<p>
  <strong>Overall Rating:</strong>
  <%= "⭐" * @restaurant.overall_rating %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @restaurant.phone_number %>
</p>





<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %> |
<%= link_to 'Meet the chef', chef_restaurant_path(@restaurant) %>

<br><br>
<%= link_to 'Write a review', new_restaurant_review_path(@restaurant)  %>

<h2>Reviews 👇</h2>
<ul>
  <% @restaurant.reviews.each do |review| %>
    <li><%= review.content %></li>
    <p><%= review.rating %> - <%= link_to 'Edit', edit_review_path(review) %> - <%= link_to 'Delete', review_path(review), method: :delete, data: {confirm: "Delete?"} %></p>
  <% end -%>
</ul>

app/views/restaurants/top.html.erb
<h1>These are our TOP restaurants</h1>

<%= render 'list' %>
<br>
<%= link_to 'Back', restaurants_path %>

app/views/reviews/_form.html.erb
<div class="row justify-content-center">
  <div class="col-6">
    <%= simple_form_for [@restaurant, @review] do |f| %>
      <%= f.input :content %>
      <%= f.input :rating, collection:[0,1,2,3,4,5] %>
      <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/reviews/edit.html.erb
<%= render 'form' %>

app/views/reviews/new.html.erb
<%= render 'form' %>